### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by hanqing1028** [starqi/ghost1001#1]
Hi! Zirui:
Im Chen in China,and I'm your cousin.rember me?
I heard that you are going to do research in AI.It's a good step,because AI is an inevitable trend in future, and i hope that you can  walk in the forefront of the times.To be honest,I'm very jealous of you,because you have received the best computer education and you can do many tings which you are good at ...
Now i become an Android Developer,not as good as you ,but ...well ..,still work hard.
Hey... i just want to say ,I support you,and your work.I also want to learn how to create a wonderful game in UNREAL engine4 or Unity 3D,I want to develop google VR app...I want to do many tings ,but i have to make a living for my fammily first. Its not easy to get my current job ,you know ,there are too many IT engineer in China, so...actually,I'm lucky ..haha
Anyway,I just want to tell you, I support you, I hope everything goes well with you.
Doing what you want to do is the happiest thing.
Good day,and Good luck.
Chen.

**Comment by starqi** [comment]
Hey :) 

Of course I remember you. How are you? My dad told me about your interest in switching to software development. On the job lists, I see a huge amount of jobs in Shanghai and Asia, so I don't think you'll have any problems at all. Similar to you, a lot of people in North America who didn't study tech are switching to programming because the industry is booming. So you're definitely not alone.

And actually, I'm not nearly as talented as you think I am. I think it's just my dad exaggerating. :) I'm still looking for a job and I'll probably be doing what you're doing - Android, or web, or if I'm LUCKY, something to do with AI (normally, you need a Master's degree). I definitely am not going to be doing research either. It's very difficult, you need a PhD (!!!), and I prefer something more practical on the business side.

Thanks for messaging. I feel guilty that you type to me in English but I can't even read Chinese. If I have any questions about Chinese or Android, I'll just ask you, OK?

**Comment by starqi** [comment]
I still have you on Skype so I'll close this...
